### ISSUE TITLE
JSBin example has no styling

### ISSUE THREAD

**Issue by ToJen** [empiricompany/bootstrap-debugger#3]
Hello @empiricompany, this is a really cool project!

The [example](https://output.jsbin.com/kipeya/3/) you gave looks like a regular HTML page. I think the links to the css file is broken.

[Here's](https://drive.google.com/file/d/0B584NUUwKdOHbS0wM1FxeW5RQjQ/view?usp=sharing) a screenshot of the console errors.

**Comment by empiricompany** [comment]
Hello @ToJen thanks!
I have modified example on jsbin https compatibile:
new url https://jsbin.com/kipeya/8
